services:
  nifi:
    image: easyglobalmarket/nifi:latest-dev
    container_name: nifi
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5050-5060:5050-5060"
    env_file:
      - path: .env.default
        required: true
      - path: .env.local
        required: true
    volumes:
      - ./certs:/opt/certs
      - conf:/opt/nifi/nifi-current/conf
      - ./scripts:/opt/scripts
      - content_repository:/opt/nifi/nifi-current/content_repository
      - database_repository:/opt/nifi/nifi-current/database_repository
      - flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - provenance_repository:/opt/nifi/nifi-current/provenance_repository

volumes:
  conf:
    driver: local
    driver_opts:
      type: none
      device: ./conf
      o: bind
  content_repository:
  database_repository:
  flowfile_repository:
  provenance_repository:
