services:
  grafana:
    container_name: grafana
    image: easyglobalmarket/stellio-grafana
    restart: unless-stopped
    environment:
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED}
      GF_SMTP_HOST: ${GF_SMTP_HOST}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS}
      GF_SMTP_FROM_NAME: ${GF_SMTP_FROM_NAME}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_SERVER_SERVE_FROM_SUB_PATH: ${GF_SERVER_SERVE_FROM_SUB_PATH}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM}
      GF_AUTH_GENERIC_OAUTH_ENABLED: ${GF_AUTH_GENERIC_OAUTH_ENABLED}
      GF_AUTH_GENERIC_OAUTH_NAME: ${GF_AUTH_GENERIC_OAUTH_NAME}
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: ${GF_AUTH_GENERIC_OAUTH_SCOPES}
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${GF_AUTH_GENERIC_OAUTH_AUTH_URL}
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${GF_AUTH_GENERIC_OAUTH_TOKEN_URL}
      GF_AUTH_GENERIC_OAUTH_API_URL: ${GF_AUTH_GENERIC_OAUTH_API_URL}
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: ${GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE}
      GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC: ${GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC}
      GF_AUTH_SIGNOUT_REDIRECT_URL: ${GF_AUTH_SIGNOUT_REDIRECT_URL}
      GF_DATE_FORMATS_FULL_DATE: ${GF_DATE_FORMATS_FULL_DATE}
      GF_DATE_FORMATS_INTERVAL_HOUR: ${GF_DATE_FORMATS_INTERVAL_HOUR}
      GF_DATE_FORMATS_INTERVAL_DAY: ${GF_DATE_FORMATS_INTERVAL_DAY}
      GF_DATE_FORMATS_INTERVAL_MONTH: ${GF_DATE_FORMATS_INTERVAL_MONTH}
      GF_FEATURE_TOGGLES_ENABLE: autoMigrateOldPanels,vizActions,ssoSettingsApi
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - type: bind
        source: ./config/stellio/hosts
        target: /etc/hosts

volumes:
  grafana-storage:
